#!/bin/bash

echo $'\n********************************************************************'
echo $'\n-------------------------Main Menu-------------------------------\n' #main menu header
echo $'********************************************************************'
PS3=$'\nWelcome to the biodiversity recording tool. Please choose one of the above options (number 1-5): ' #PS3 menu used to select options
echo $'\n'
options=($'Add a new recording of a species' $'Remove an existing species record' $'Search for species' $'Email recorder(s)' $'Quit') #options available
select choice in "${options[@]}"
do
        case $choice in #listing cases
                "Add a new recording of a species")
                        ./add.sh #brings to add menu
			break
                        ;;

                "Remove an existing species record")
                        ./remove.sh #brings to remove menu
                        break
			;;

                "Search for species")
                        ./search.sh #brings to search menu
                        break
			;;

                "Email recorder(s)")
                        ./email.sh #brings to email menu
                        break
			;;

                "Quit")
                        echo $'\nGood bye!\n'
			echo $'---------------'
                        break
                        exit #quits the programme
                        ;;
                *) echo $'\nInvalid option. Please enter a number 1-5\n';; #catches errors in user entry
        esac
done
